spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:feature_server_db
    username: sa
    password: ''
  h2:
    console.enabled: true
  flyway:
    locations: [classpath:db/migration/local]