spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_URL:localhost:5432}/${POSTGRES_DATABASE:feature-server}
    username: ${POSTGRES_USERNAME:admin}
    password: ${POSTGRES_PASSWORD:admin}
  flyway:
    locations: [classpath:db/migration/dev]

ff4j:
  cache-manager:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}